language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - wget "https://github.com/google/protobuf/releases/download/v3.0.2/protobuf-python-3.0.2.tar.gz"
  - tar xzf protobuf-python-3.0.2.tar.gz
  - pushd protobuf-3.0.2 && ./configure --prefix=/usr && make && sudo make install && popd
# command to install dependencies
install: "make init"
# command to run tests
script: "make test"
